stages:
  - test
  - release

test:
  stage: test
  image: node:14
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install
    - npm run test
    - npm run build:ts

release:
  stage: release
  image: node:14
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install
    - npm run release
  only:
    - tags
